import { useState, type FormEvent } from 'react'
import { FlaskConical, X } from 'lucide-react'

type Mode = 'RECOMMENDATION' | 'DEMAND_CHANGE'
type Props = { open: boolean; onClose: () => void; onSubmit: (data: Record<string, unknown>) => Promise<void>; busy: boolean }
type State = Record<string, string | number>

const defaults: State = { name: 'Evaluator Custom Scenario', sku: 'CUSTOM-01', productName: 'Custom Operational Item', unitVolume: 2, nodeCode: 'BLR-01', nodeName: 'Bengaluru FC', recommendedQty: 800, onHand: 100, reserved: 0, damaged: 0, baseline: 500, revised: 900, s1Code: 'SUP-01', s1Name: 'Primary Vendor', s1Cost: 1200, s1Reliability: 9700, s1Max: 300, s2Code: 'SUP-02', s2Name: 'Alternate Vendor', s2Cost: 1350, s2Reliability: 9200, s2Max: 500, budget: 1000000, storage: 5000, safety: 50 }
const numeric = new Set(['unitVolume', 'recommendedQty', 'onHand', 'reserved', 'damaged', 'baseline', 'revised', 's1Cost', 's1Reliability', 's1Max', 's2Cost', 's2Reliability', 's2Max', 'budget', 'storage', 'safety'])

export function CustomScenarioModal({ open, onClose, onSubmit, busy }: Props) {
  const [mode, setMode] = useState<Mode>('RECOMMENDATION')
  const [fields, setFields] = useState<State>(defaults)
  if (!open) return null
  const update = (key: string, value: string) => setFields(current => ({ ...current, [key]: numeric.has(key) ? Number(value) : value }))
  const field = (key: string, label: string, min = 0) => <div className="form-field"><label>{label}</label><input type={numeric.has(key) ? 'number' : 'text'} min={numeric.has(key) ? min : undefined} value={fields[key]} onChange={event => update(key, event.target.value)} required /></div>
  const supplier = (prefix: 's1' | 's2', title: string) => <><div className="form-section-title">{title}</div>{field(`${prefix}Code`, 'Code')}{field(`${prefix}Name`, 'Name')}{field(`${prefix}Cost`, 'Unit Cost (Minor: ₹1 = 100)', 1)}{field(`${prefix}Max`, 'Max Quantity')}{field(`${prefix}Reliability`, 'Reliability BPS (0-10000)')}</>
  const submit = async (event: FormEvent) => {
    event.preventDefault()
    const now = new Date()
    const supplierData = (prefix: 's1' | 's2', leadTime: number) => ({ code: fields[`${prefix}Code`], name: fields[`${prefix}Name`], reliability_score_bps: fields[`${prefix}Reliability`], unit_cost_minor: fields[`${prefix}Cost`], currency: 'INR', minimum_order_quantity: 25, lead_time_days: leadTime, max_available_quantity: fields[`${prefix}Max`] })
    await onSubmit({ name: fields.name, mode, product: { sku: fields.sku, name: fields.productName, unit_volume: fields.unitVolume }, node: { code: fields.nodeCode, name: fields.nodeName }, recommended_quantity: fields.recommendedQty, inventory: { on_hand: fields.onHand, reserved: fields.reserved, damaged: fields.damaged }, forecasts: { baseline: fields.baseline, revised: mode === 'DEMAND_CHANGE' ? fields.revised : null, window_start: now.toISOString(), window_end: new Date(now.getTime() + 7 * 24 * 3600 * 1000).toISOString() }, suppliers: [supplierData('s1', 2), supplierData('s2', 3)], budget: { available_minor: fields.budget, currency: 'INR' }, storage: { available_volume: fields.storage }, policy: { safety_stock: fields.safety, review_period_days: 2 }, recent_sales: mode === 'DEMAND_CHANGE' ? { units_sold: 280, window_hours: 24 } : null })
  }
  return <div className="modal-backdrop" role="presentation"><section className="modal custom-lab-modal" role="dialog" aria-modal="true" aria-labelledby="custom-lab-title"><button className="modal-close" onClick={onClose} aria-label="Close"><X size={18} /></button><span className="modal-icon"><FlaskConical size={19} /></span><h2 id="custom-lab-title">Custom Scenario Lab</h2><p>Define operational constraints and test multi-supplier or demand-spike intelligence live without writing code.</p><form onSubmit={submit}><div className="custom-form-grid"><div className="form-field form-field-full"><label>Scenario Name</label><input value={fields.name} onChange={event => update('name', event.target.value)} required /></div><div className="form-field form-field-full"><label>Evaluation Mode</label><select value={mode} onChange={event => setMode(event.target.value as Mode)}><option value="RECOMMENDATION">Standard / Multi-Supplier Recommendation</option><option value="DEMAND_CHANGE">Demand Spike Change (24h sales jump)</option></select></div><div className="form-section-title">Product & Node</div>{field('sku', 'SKU')}{field('productName', 'Product Name')}{field('nodeCode', 'Node Code')}{field('nodeName', 'Node Name')}{field('unitVolume', 'Unit Volume (m³)', 1)}{field('recommendedQty', 'Recommended Qty')}<div className="form-section-title">Inventory & Forecast</div>{field('onHand', 'Usable On-Hand')}{field('reserved', 'Reserved Units')}{field('damaged', 'Damaged Units')}{field('baseline', 'Baseline Forecast')}{mode === 'DEMAND_CHANGE' && field('revised', 'Revised Forecast (Spike)')}{supplier('s1', 'Supplier 1 (Primary)')}{supplier('s2', 'Supplier 2 (Secondary / Alternate)')}<div className="form-section-title">Global Physical Limits</div>{field('budget', 'Available Budget (Minor: ₹1 = 100)')}{field('storage', 'Available Storage Volume')}{field('safety', 'Safety Stock')}</div><div className="modal-actions"><button type="button" className="secondary-button" onClick={onClose}>Cancel</button><button type="submit" className="primary-button" disabled={busy}>{busy ? 'Creating custom scenario…' : 'Run Custom Scenario'}</button></div></form></section></div>
}
