import { Boxes } from 'lucide-react'
import type { SourcingPlan } from '../api'

const money = (value: number, currency: string) => new Intl.NumberFormat('en-IN', { style: 'currency', currency, maximumFractionDigits: 2 }).format(value / 100)
const humanize = (value: string) => value.toLowerCase().replaceAll('_', ' ').replace(/\b\w/g, char => char.toUpperCase())

export function SourcingPlanView({ plan }: { plan: SourcingPlan }) {
  return <div className="section-block sourcing-plan-block"><div className="section-title"><div><h3>Sourcing allocation plan</h3><p>Allocating {plan.total_quantity.toLocaleString()} of {plan.raw_need.toLocaleString()} required units</p></div><span className="policy-tag"><Boxes size={13} />v{plan.version} · {money(plan.total_cost_minor, plan.currency)}</span></div><div className="sourcing-table-wrap"><table className="sourcing-table"><thead><tr><th>#</th><th>Supplier</th><th>Allocated Qty</th><th>Unit Cost</th><th>Total Cost</th><th>Delivery</th><th>Order ID</th></tr></thead><tbody>{plan.lines.map(line => <tr key={line.id}><td>{line.line_number}</td><td className="font-mono">{line.supplier_id.slice(0, 8)}</td><td><strong>{line.allocated_quantity.toLocaleString()}</strong></td><td>{money(line.unit_cost_minor, line.currency)}</td><td>{money(line.total_cost_minor, line.currency)}</td><td>{line.expected_delivery_at ? new Date(line.expected_delivery_at).toLocaleDateString('en-IN') : '—'}</td><td><span className="po-pill">{line.purchase_order_id ? `#${line.purchase_order_id.slice(0, 8)}` : 'Pending PO'}</span></td></tr>)}</tbody></table></div>{plan.supplier_assessments.length > 0 && <div className="supplier-assessments"><small className="assessments-title">Supplier Eligibility Assessments</small><div className="assessments-grid">{plan.supplier_assessments.map((assessment, index) => <div key={index} className={`assessment-card ${assessment.eligible ? 'eligible' : 'ineligible'}`}><div className="assessment-top"><span className="font-mono">{assessment.supplier_id.slice(0, 8)}</span><span className={`status-pill ${assessment.eligible ? 'complete' : 'rejected'}`}>{assessment.eligible ? 'Eligible' : 'Excluded'}</span></div>{assessment.reason_codes.length > 0 && <div className="reason-codes">{assessment.reason_codes.map(code => <span key={code} className="reason-code-tag">{humanize(code)}</span>)}</div>}</div>)}</div></div>}</div>
}
