"""add expansion schema

Revision ID: 737ea043a94f
Revises: 3f0b78c31703
Create Date: 2026-09-13 17:00:47.995538
"""
import sqlalchemy as sa
from alembic import op

revision = '737ea043a94f'
down_revision = '3f0b78c31703'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_observations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('units_sold', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_version', sa.String(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'node_id', 'window_start', 'window_end', 'source_version', name='uq_sales_observation')
    )
    op.create_index(op.f('ix_sales_observations_node_id'), 'sales_observations', ['node_id'], unique=False)
    op.create_index(op.f('ix_sales_observations_product_id'), 'sales_observations', ['product_id'], unique=False)
    op.create_table('demand_signals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('external_event_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('sales_observation_id', sa.String(), nullable=True),
    sa.Column('baseline_forecast_id', sa.String(), nullable=True),
    sa.Column('revised_forecast_id', sa.String(), nullable=True),
    sa.Column('actual_to_baseline_ratio_bps', sa.Integer(), nullable=False),
    sa.Column('threshold_bps', sa.Integer(), nullable=False),
    sa.Column('source_version', sa.String(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['baseline_forecast_id'], ['forecasts.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['revised_forecast_id'], ['forecasts.id'], ),
    sa.ForeignKeyConstraint(['sales_observation_id'], ['sales_observations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_event_id')
    )
    op.create_index(op.f('ix_demand_signals_node_id'), 'demand_signals', ['node_id'], unique=False)
    op.create_index(op.f('ix_demand_signals_product_id'), 'demand_signals', ['product_id'], unique=False)
    op.create_table('investigation_traces',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('review_id', sa.String(), nullable=False),
    sa.Column('scenario_type', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('allowed_tools_json', sa.JSON(), nullable=False),
    sa.Column('mandatory_manifest_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('rounds_used', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['purchasing_reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_traces_review_id'), 'investigation_traces', ['review_id'], unique=False)
    op.create_table('agent_tool_calls',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('investigation_trace_id', sa.String(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(), nullable=False),
    sa.Column('arguments_json', sa.JSON(), nullable=False),
    sa.Column('arguments_hash', sa.String(), nullable=False),
    sa.Column('result_ref', sa.String(), nullable=True),
    sa.Column('result_hash', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_trace_id'], ['investigation_traces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('investigation_trace_id', 'sequence', name='uq_tool_trace_sequence')
    )
    op.create_index(op.f('ix_agent_tool_calls_investigation_trace_id'), 'agent_tool_calls', ['investigation_trace_id'], unique=False)
    op.create_table('sourcing_plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('review_id', sa.String(), nullable=False),
    sa.Column('decision_id', sa.String(), nullable=True),
    sa.Column('evidence_snapshot_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('raw_need', sa.Integer(), nullable=False),
    sa.Column('total_quantity', sa.Integer(), nullable=False),
    sa.Column('total_cost_minor', sa.Integer(), nullable=False),
    sa.Column('need_by_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('allocation_policy_version', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.ForeignKeyConstraint(['evidence_snapshot_id'], ['evidence_snapshots.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['review_id'], ['purchasing_reviews.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id', 'version', name='uq_sourcing_plan_review_version')
    )
    op.create_index(op.f('ix_sourcing_plans_review_id'), 'sourcing_plans', ['review_id'], unique=False)
    op.create_table('purchase_proposals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('review_id', sa.String(), nullable=False),
    sa.Column('decision_id', sa.String(), nullable=False),
    sa.Column('sourcing_plan_id', sa.String(), nullable=True),
    sa.Column('proposal_version', sa.Integer(), nullable=False),
    sa.Column('evidence_snapshot_hash', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.ForeignKeyConstraint(['review_id'], ['purchasing_reviews.id'], ),
    sa.ForeignKeyConstraint(['sourcing_plan_id'], ['sourcing_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id', 'proposal_version', name='uq_proposal_review_version')
    )
    op.create_index(op.f('ix_purchase_proposals_review_id'), 'purchase_proposals', ['review_id'], unique=False)
    op.create_table('sourcing_option_assessments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sourcing_plan_id', sa.String(), nullable=False),
    sa.Column('supplier_id', sa.String(), nullable=False),
    sa.Column('eligible', sa.Boolean(), nullable=False),
    sa.Column('exclusion_reason_codes_json', sa.JSON(), nullable=False),
    sa.Column('normalized_terms_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['sourcing_plan_id'], ['sourcing_plans.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sourcing_plan_id', 'supplier_id', name='uq_assessment_supplier')
    )
    op.create_index(op.f('ix_sourcing_option_assessments_sourcing_plan_id'), 'sourcing_option_assessments', ['sourcing_plan_id'], unique=False)
    op.create_table('sourcing_plan_lines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sourcing_plan_id', sa.String(), nullable=False),
    sa.Column('supplier_id', sa.String(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost_minor', sa.Integer(), nullable=False),
    sa.Column('total_cost_minor', sa.Integer(), nullable=False),
    sa.Column('minimum_order_quantity', sa.Integer(), nullable=False),
    sa.Column('reliability_score_bps', sa.Integer(), nullable=False),
    sa.Column('expected_delivery_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inclusion_reason_codes_json', sa.JSON(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['sourcing_plan_id'], ['sourcing_plans.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('sourcing_plan_id', 'supplier_id', name='uq_plan_supplier')
    )
    op.create_index(op.f('ix_sourcing_plan_lines_sourcing_plan_id'), 'sourcing_plan_lines', ['sourcing_plan_id'], unique=False)
    op.add_column('action_attempts', sa.Column('sourcing_plan_line_id', sa.String(), nullable=True))
    op.add_column('purchasing_reviews', sa.Column('scenario_type', sa.String(), nullable=False, server_default='recommendation-review'))
    op.alter_column('purchasing_reviews', 'recommendation_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('suppliers', sa.Column('reliability_score_bps', sa.Integer(), nullable=False, server_default='9500'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'reliability_score_bps')
    op.alter_column('purchasing_reviews', 'recommendation_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('purchasing_reviews', 'scenario_type')
    op.drop_column('action_attempts', 'sourcing_plan_line_id')
    op.drop_index(op.f('ix_sourcing_plan_lines_sourcing_plan_id'), table_name='sourcing_plan_lines')
    op.drop_table('sourcing_plan_lines')
    op.drop_index(op.f('ix_sourcing_option_assessments_sourcing_plan_id'), table_name='sourcing_option_assessments')
    op.drop_table('sourcing_option_assessments')
    op.drop_index(op.f('ix_purchase_proposals_review_id'), table_name='purchase_proposals')
    op.drop_table('purchase_proposals')
    op.drop_index(op.f('ix_sourcing_plans_review_id'), table_name='sourcing_plans')
    op.drop_table('sourcing_plans')
    op.drop_index(op.f('ix_agent_tool_calls_investigation_trace_id'), table_name='agent_tool_calls')
    op.drop_table('agent_tool_calls')
    op.drop_index(op.f('ix_investigation_traces_review_id'), table_name='investigation_traces')
    op.drop_table('investigation_traces')
    op.drop_index(op.f('ix_demand_signals_product_id'), table_name='demand_signals')
    op.drop_index(op.f('ix_demand_signals_node_id'), table_name='demand_signals')
    op.drop_table('demand_signals')
    op.drop_index(op.f('ix_sales_observations_product_id'), table_name='sales_observations')
    op.drop_index(op.f('ix_sales_observations_node_id'), table_name='sales_observations')
    op.drop_table('sales_observations')
    # ### end Alembic commands ###

